// Code generated by Kitex v0.3.1. DO NOT EDIT.

package videoservice

import (
	"context"
	"github.com/cloudwego/kitex/client"
	"github.com/cloudwego/kitex/client/callopt"
	"micro_tiktok/kitex_gen/video"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	Feed(ctx context.Context, Req *video.FeedRequest, callOptions ...callopt.Option) (r *video.FeedResponse, err error)
	Publish(ctx context.Context, Req *video.PublishRequest, callOptions ...callopt.Option) (r *video.PublishResponse, err error)
	List(ctx context.Context, Req *video.ListRequest, callOptions ...callopt.Option) (r *video.ListResponse, err error)
	MGet(ctx context.Context, Req *video.MGetRequest, callOptions ...callopt.Option) (r *video.MGetResponse, err error)
	QueryByVid(ctx context.Context, Req *video.QueryByVidRequest, callOptions ...callopt.Option) (r *video.QueryByVidResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kVideoServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kVideoServiceClient struct {
	*kClient
}

func (p *kVideoServiceClient) Feed(ctx context.Context, Req *video.FeedRequest, callOptions ...callopt.Option) (r *video.FeedResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Feed(ctx, Req)
}

func (p *kVideoServiceClient) Publish(ctx context.Context, Req *video.PublishRequest, callOptions ...callopt.Option) (r *video.PublishResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Publish(ctx, Req)
}

func (p *kVideoServiceClient) List(ctx context.Context, Req *video.ListRequest, callOptions ...callopt.Option) (r *video.ListResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.List(ctx, Req)
}

func (p *kVideoServiceClient) MGet(ctx context.Context, Req *video.MGetRequest, callOptions ...callopt.Option) (r *video.MGetResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.MGet(ctx, Req)
}

func (p *kVideoServiceClient) QueryByVid(ctx context.Context, Req *video.QueryByVidRequest, callOptions ...callopt.Option) (r *video.QueryByVidResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.QueryByVid(ctx, Req)
}
