// Code generated by Kitex v0.3.1. DO NOT EDIT.

package commentvideoservice

import (
	"context"
	"github.com/cloudwego/kitex/client"
	"github.com/cloudwego/kitex/client/callopt"
	"micro_tiktok/kitex_gen/comment"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	Comment(ctx context.Context, Req *comment.CommentRequest, callOptions ...callopt.Option) (r *comment.CommentResponse, err error)
	List(ctx context.Context, Req *comment.CommentListRequest, callOptions ...callopt.Option) (r *comment.CommentListResponse, err error)
	CountRes(ctx context.Context, Req *comment.CommentCountRequest, callOptions ...callopt.Option) (r *comment.CommentCountResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kCommentVideoServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kCommentVideoServiceClient struct {
	*kClient
}

func (p *kCommentVideoServiceClient) Comment(ctx context.Context, Req *comment.CommentRequest, callOptions ...callopt.Option) (r *comment.CommentResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Comment(ctx, Req)
}

func (p *kCommentVideoServiceClient) List(ctx context.Context, Req *comment.CommentListRequest, callOptions ...callopt.Option) (r *comment.CommentListResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.List(ctx, Req)
}

func (p *kCommentVideoServiceClient) CountRes(ctx context.Context, Req *comment.CommentCountRequest, callOptions ...callopt.Option) (r *comment.CommentCountResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CountRes(ctx, Req)
}
