// Code generated by Kitex v0.3.1. DO NOT EDIT.

package relationservice

import (
	"context"
	"github.com/cloudwego/kitex/client"
	"github.com/cloudwego/kitex/client/callopt"
	"micro_tiktok/kitex_gen/relation"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	Action(ctx context.Context, Req *relation.ActionRequest, callOptions ...callopt.Option) (r *relation.ActionResponse, err error)
	List(ctx context.Context, Req *relation.ListRequest, callOptions ...callopt.Option) (r *relation.ListResponse, err error)
	Info(ctx context.Context, Req *relation.InfoRequest, callOptions ...callopt.Option) (r *relation.InfoResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kRelationServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kRelationServiceClient struct {
	*kClient
}

func (p *kRelationServiceClient) Action(ctx context.Context, Req *relation.ActionRequest, callOptions ...callopt.Option) (r *relation.ActionResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Action(ctx, Req)
}

func (p *kRelationServiceClient) List(ctx context.Context, Req *relation.ListRequest, callOptions ...callopt.Option) (r *relation.ListResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.List(ctx, Req)
}

func (p *kRelationServiceClient) Info(ctx context.Context, Req *relation.InfoRequest, callOptions ...callopt.Option) (r *relation.InfoResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Info(ctx, Req)
}
