version: '3'

services:
  mysql:
    image: "mysql:latest"
    ports:
      - "13306:3306"
    environment:
      - MYSQL_DATABASE=micro_tiktok
      - MYSQL_USER=mtt
      - MYSQL_PASSWORD=4&o4csZZ^OMDiy1Q
      - MYSQL_RANDOM_ROOT_PASSWORD="yes"
  Etcd:
    image: "bitnami/etcd:latest"
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
    ports:
      - "12379:2379"
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "6831:6831/udp"
      - "16686:16686"
  Redis:
    image: "redis:latest"
    restart: always
    ports:
      - "16379:6379"