package handlers

import (
	"github.com/gin-gonic/gin"
	"net/http"
)

type AutoGenerated struct {
	StatusCode int         `json:"status_code"`
	StatusMsg  string      `json:"status_msg"`
	NextTime   int         `json:"next_time"`
	VideoList  []VideoList `json:"video_list"`
}
type Author struct {
	ID            int    `json:"id"`
	Name          string `json:"name"`
	FollowCount   int    `json:"follow_count"`
	FollowerCount int    `json:"follower_count"`
	IsFollow      bool   `json:"is_follow"`
}
type VideoList struct {
	ID            int    `json:"id"`
	Author        Author `json:"author"`
	PlayURL       string `json:"play_url"`
	CoverURL      string `json:"cover_url"`
	FavoriteCount int    `json:"favorite_count"`
	CommentCount  int    `json:"comment_count"`
	IsFavorite    bool   `json:"is_favorite"`
	Title         string `json:"title"`
}

func MockVideo(c *gin.Context) {
	c.JSON(http.StatusOK, AutoGenerated{
		StatusCode: 0,
		StatusMsg:  "",
		NextTime:   0,
		VideoList: []VideoList{
			VideoList{
				ID: 1,
				Author: Author{
					ID:            1,
					Name:          "1111111",
					FollowCount:   0,
					FollowerCount: 0,
					IsFollow:      false,
				},
				PlayURL:       "https://data.mtt.dtpark.top/video%2F22%2F06%2F06%2F0dc38da5db9244bb4a9d831fe2fd2dc8.mp4",
				CoverURL:      "https://data.mtt.dtpark.top/cover/video%2F22%2F06%2F06%2F0dc38da5db9244bb4a9d831fe2fd2dc8.jpg",
				FavoriteCount: 0,
				CommentCount:  0,
				IsFavorite:    false,
				Title:         "1111111",
			},
		},
	})
}
