// Code generated by Kitex v0.3.1. DO NOT EDIT.

package favoritevideoservice

import (
	"context"
	"github.com/cloudwego/kitex/client"
	"github.com/cloudwego/kitex/client/callopt"
	"micro_tiktok/kitex_gen/favorite"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	Favorite(ctx context.Context, Req *favorite.FavoriteRequest, callOptions ...callopt.Option) (r *favorite.FavoriteResponse, err error)
	FavoriteList(ctx context.Context, Req *favorite.FavoriteListRequest, callOptions ...callopt.Option) (r *favorite.FavoriteListResponse, err error)
	GetFavoriteCount(ctx context.Context, Req *favorite.VideoFavoriteCountRequest, callOptions ...callopt.Option) (r *favorite.VideoFavoriteCountResponse, err error)
	IsFavoriteVideo(ctx context.Context, Req *favorite.IsFavoriteVideoRequest, callOptions ...callopt.Option) (r *favorite.IsFavoriteVideoResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kFavoriteVideoServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kFavoriteVideoServiceClient struct {
	*kClient
}

func (p *kFavoriteVideoServiceClient) Favorite(ctx context.Context, Req *favorite.FavoriteRequest, callOptions ...callopt.Option) (r *favorite.FavoriteResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Favorite(ctx, Req)
}

func (p *kFavoriteVideoServiceClient) FavoriteList(ctx context.Context, Req *favorite.FavoriteListRequest, callOptions ...callopt.Option) (r *favorite.FavoriteListResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.FavoriteList(ctx, Req)
}

func (p *kFavoriteVideoServiceClient) GetFavoriteCount(ctx context.Context, Req *favorite.VideoFavoriteCountRequest, callOptions ...callopt.Option) (r *favorite.VideoFavoriteCountResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetFavoriteCount(ctx, Req)
}

func (p *kFavoriteVideoServiceClient) IsFavoriteVideo(ctx context.Context, Req *favorite.IsFavoriteVideoRequest, callOptions ...callopt.Option) (r *favorite.IsFavoriteVideoResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.IsFavoriteVideo(ctx, Req)
}
